apiVersion: v1
kind: Service
metadata:
  name: {{ include "status.fullname" . }}
  labels:
    {{- include "status.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "status.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "status.fullname" . }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- with .Values.ingress.className }}ingressClassName: {{ . }}{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "status.fullname" $ }}
                port: { name: http }
        {{- end }}
  {{- end }}
  {{- with .Values.ingress.tls }}tls: {{ toYaml . | nindent 4 }}{{- end }}
{{- end }}
{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "status.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "status.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {{ toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
      ports:
        - { protocol: TCP, port: 3000 }
  egress:
    - to:
      {{- range .Values.networkPolicy.egressCidrs }}
        - ipBlock: { cidr: {{ . | quote }} }
      {{- end }}
{{- end }}
