import Link from "next/link";
import { requireSession } from "@/lib/require-session";
import { getScopedPages, sessionHasCapability } from "@/lib/admin-guard";
import { publicPagePath } from "@/lib/public-path";

export default async function PagesListPage() {
  const { session, org } = await requireSession();
  const pages = await getScopedPages(session, org.id);
  const canConfigure = sessionHasCapability(session, "page.configure");
  return <div className="mx-auto w-full max-w-6xl space-y-6"><header className="flex flex-col gap-4 border-b border-[var(--line)] pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-[var(--cyan)]">Organization console</p><h1 className="mt-2 font-mono text-2xl font-semibold">Status pages</h1><p className="mt-2 text-sm text-[var(--fg-soft)]">Keep your customers informed about service health and incidents.</p></div>{canConfigure && <Link href="/organization/pages/new" className="rounded-md bg-[var(--cyan)] px-5 py-2.5 text-center text-sm font-semibold text-[var(--on-cyan)]">Create page</Link>}</header><div className="space-y-3">{pages.map((page) => { const state = page.setupCompletedAt === null ? "Draft" : page.publicVisible ? "Published" : "Hidden"; return <article key={page.id} className="flex flex-col gap-3 border border-[var(--line)] bg-[var(--surface)] p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="font-semibold">{page.name}</h2><span className="bg-[var(--surface-raised)] px-2 py-0.5 text-[10px] font-semibold uppercase">{page.isHub ? "Hub" : page.type.toLowerCase()}</span><span className={`px-2 py-0.5 text-[10px] font-semibold uppercase ${state === "Published" ? "bg-[var(--green-soft)] text-[var(--green)]" : "bg-[var(--amber-soft)] text-[var(--amber)]"}`}>{state}</span></div><p className="mt-1 font-mono text-xs text-[var(--fg-dim)]">/{page.slug}</p></div><div className="flex gap-2">{page.isHub && canConfigure && <Link href={`/organization/pages/new?hubParentId=${page.id}`} className="border border-[var(--line)] px-3 py-1.5 text-xs font-semibold">Create status page in this hub</Link>}{page.publicVisible && page.setupCompletedAt && <a href={publicPagePath(page)} target="_blank" rel="noreferrer" className="border border-[var(--line)] px-3 py-1.5 text-xs font-semibold">View</a>}{canConfigure && <Link href={`/organization/pages/${page.id}`} className="border border-[var(--cyan)]/30 px-3 py-1.5 text-xs font-semibold text-[var(--cyan)]">{state === "Draft" ? "Continue setup" : "Manage"}</Link>}</div></article>; })}{pages.length === 0 && <div className="border border-dashed border-[var(--line-bright)] p-8 text-center text-sm text-[var(--fg-dim)]">No status pages yet.</div>}</div></div>;
}
