"use client";

import { Children, isValidElement, useCallback, useEffect, useId, useMemo, useRef, useState, type ChangeEvent, type CSSProperties, type ReactNode, type SelectHTMLAttributes } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronsUpDown } from "lucide-react";
import { fieldClass } from "@/components/ui/input";
import { cn } from "@/lib/utils";

type SelectOption = { disabled: boolean; label: string; value: string };
type MenuPlacement = "above" | "below";
type MenuPosition = CSSProperties & { maxHeight: number; width: number };
type LayoutInput = { contentWidth: number; optionCount: number; trigger: { bottom: number; left: number; right: number; top: number; width: number }; viewportHeight: number; viewportWidth: number };

export function calculateSelectMenuLayout({ contentWidth, optionCount, trigger, viewportHeight, viewportWidth }: LayoutInput) {
  const inset = 8; const gap = 6; const width = Math.min(viewportWidth - inset * 2, Math.max(Math.ceil(trigger.width), contentWidth));
  const left = Math.max(inset, Math.min(trigger.left, viewportWidth - inset - width)); const estimated = Math.min(320, optionCount * 38 + 8);
  const below = viewportHeight - trigger.bottom - gap - inset; const above = trigger.top - gap - inset; const placement: MenuPlacement = below >= Math.min(estimated, 180) || below >= above ? "below" : "above"; const available = placement === "below" ? below : above;
  return { placement, position: { left: Math.round(left), width: Math.round(width), maxHeight: Math.round(Math.max(72, Math.min(320, Math.max(0, available)))), ...(placement === "below" ? { top: Math.min(viewportHeight - inset, trigger.bottom + gap) } : { bottom: Math.max(inset, viewportHeight - trigger.top + gap) }) } as MenuPosition };
}

function textOf(node: ReactNode): string { if (typeof node === "string" || typeof node === "number") return String(node); if (Array.isArray(node)) return node.map(textOf).join(""); if (isValidElement<{ children?: ReactNode }>(node)) return textOf(node.props.children); return ""; }
function optionsFromChildren(children: ReactNode): SelectOption[] { const options: SelectOption[] = []; Children.forEach(children, (child) => { if (!isValidElement<{ children?: ReactNode; disabled?: boolean; value?: string | number }>(child) || child.type !== "option") return; const label = textOf(child.props.children); options.push({ label, value: String(child.props.value ?? label), disabled: Boolean(child.props.disabled) }); }); return options; }

export function Select({ children, className, defaultValue, disabled, form, id, name, onChange, required, title, value, "aria-label": ariaLabel, "aria-labelledby": ariaLabelledBy }: Omit<SelectHTMLAttributes<HTMLSelectElement>, "multiple" | "size">) {
  const options = useMemo(() => optionsFromChildren(children), [children]); const first = options.find((option) => !option.disabled)?.value ?? ""; const controlled = value === undefined ? undefined : String(value); const [internal, setInternal] = useState(String(controlled ?? defaultValue ?? first)); const selected = options.some((option) => option.value === (controlled ?? internal)) ? (controlled ?? internal) : first; const selectedOption = options.find((option) => option.value === selected); const [open, setOpen] = useState(false); const [active, setActive] = useState(Math.max(0, options.findIndex((option) => option.value === selected))); const rootRef = useRef<HTMLDivElement>(null); const buttonRef = useRef<HTMLButtonElement>(null); const menuRef = useRef<HTMLDivElement>(null); const hiddenRef = useRef<HTMLInputElement>(null); const listId = useId(); const [position, setPosition] = useState<MenuPosition>({ left: 8, top: 8, width: 160, maxHeight: 320 });
  const reposition = useCallback(() => { const button = buttonRef.current; if (!button) return; const rect = button.getBoundingClientRect(); const canvas = document.createElement("canvas"); const ctx = canvas.getContext("2d"); const computed = getComputedStyle(button); if (ctx) ctx.font = `${computed.fontWeight} ${computed.fontSize} ${computed.fontFamily}`; const longest = options.reduce((max, option) => Math.max(max, ctx?.measureText(option.label).width ?? 0), 0); const result = calculateSelectMenuLayout({ contentWidth: Math.ceil(longest + 70), optionCount: options.length, trigger: rect, viewportHeight: innerHeight, viewportWidth: innerWidth }); setPosition(result.position); }, [options]);
  useEffect(() => { const formElement = hiddenRef.current?.form; if (!formElement) return; const reset = () => { if (controlled === undefined) setInternal(String(defaultValue ?? first)); }; formElement.addEventListener("reset", reset); return () => formElement.removeEventListener("reset", reset); }, [controlled, defaultValue, first]);
  useEffect(() => { if (!open) return; reposition(); const dismiss = (event: PointerEvent) => { const target = event.target as Node; if (!rootRef.current?.contains(target) && !menuRef.current?.contains(target)) setOpen(false); }; const repositionOnScroll = () => reposition(); document.addEventListener("pointerdown", dismiss); addEventListener("resize", repositionOnScroll); addEventListener("scroll", repositionOnScroll, true); requestAnimationFrame(() => menuRef.current?.focus()); return () => { document.removeEventListener("pointerdown", dismiss); removeEventListener("resize", repositionOnScroll); removeEventListener("scroll", repositionOnScroll, true); }; }, [open, reposition]);
  function choose(next: string) { if (controlled === undefined) setInternal(next); const target = { name: name ?? "", value: next } as EventTarget & HTMLSelectElement; onChange?.({ currentTarget: target, target } as ChangeEvent<HTMLSelectElement>); setOpen(false); requestAnimationFrame(() => buttonRef.current?.focus()); }
  function onKeyDown(event: React.KeyboardEvent) { if (event.key === "Escape") { event.preventDefault(); setOpen(false); buttonRef.current?.focus(); return; } if (!open && ["ArrowDown", "ArrowUp", "Enter", " "].includes(event.key)) { event.preventDefault(); setOpen(true); setActive(Math.max(0, options.findIndex((option) => option.value === selected))); return; } if (open && (event.key === "ArrowDown" || event.key === "ArrowUp")) { event.preventDefault(); const direction = event.key === "ArrowDown" ? 1 : -1; let next = active; do { next = (next + direction + options.length) % options.length; } while (options[next]?.disabled && next !== active); setActive(next); } else if (open && (event.key === "Enter" || event.key === " ")) { event.preventDefault(); if (options[active] && !options[active].disabled) choose(options[active].value); } }
  return <><div ref={rootRef} className="relative min-w-0" style={{ width: /(?:^|\s)(?:[a-z]+:)*w-full(?:\s|$)/.test(className ?? "") ? "100%" : undefined }}><button ref={buttonRef} type="button" id={id} disabled={disabled || !options.length} aria-label={ariaLabel} aria-labelledby={ariaLabelledBy} aria-controls={open ? listId : undefined} aria-expanded={open} aria-haspopup="listbox" aria-required={required || undefined} role="combobox" title={title} onClick={() => { if (!open) reposition(); setOpen((current) => !current); }} onKeyDown={onKeyDown} className={cn(fieldClass, "h-9 items-center justify-between gap-3 py-2 text-left [&_svg]:text-primary", className)}><span className="min-w-0 truncate">{selectedOption?.label}</span><ChevronsUpDown aria-hidden size={15} className={cn("shrink-0 transition-transform", open && "rotate-180")} /></button></div>{open && typeof document !== "undefined" && createPortal(<div ref={menuRef} id={listId} role="listbox" tabIndex={-1} aria-label={ariaLabel} aria-labelledby={ariaLabelledBy} onKeyDown={onKeyDown} style={position} className="fixed z-[2000] box-border min-w-0 animate-pop overflow-y-auto overscroll-contain rounded-card border border-line bg-surface p-1.5 text-base text-ink shadow-float">{options.map((option, index) => <button key={`${option.value}-${index}`} type="button" role="option" aria-selected={option.value === selected} disabled={option.disabled} className={cn("flex min-h-10 w-full cursor-pointer items-center gap-3 rounded-control px-3 text-left text-sm transition-colors duration-100 disabled:cursor-not-allowed disabled:opacity-45 max-sm:min-h-11", index === active && "bg-sunken", option.value === selected && "bg-primary-soft font-semibold text-primary-ink")} onMouseEnter={() => setActive(index)} onClick={() => choose(option.value)}><span className="min-w-0 flex-1 truncate">{option.label}</span>{option.value === selected && <Check aria-hidden size={15} className="text-primary" />}</button>)}</div>, document.body)}<input ref={hiddenRef} type="hidden" name={name} form={form} value={selected} disabled={disabled} /></>;
}
