export const DEFAULT_MONITOR_TEMPLATES = [
  {
    name: "GitHub Status API",
    category: "Developer tools",
    description: "Checks the provider's documented service-health summary endpoint.",
    type: "KEYWORD",
    target: "https://www.githubstatus.com/api/v2/status.json",
    port: null,
    expectedStatusRange: "200-299",
    keywordMatch: "\"indicator\"",
    enabled: true,
  },
  {
    name: "Cloudflare Status API",
    category: "Cloud infrastructure",
    description: "Checks the provider's documented service-health summary endpoint.",
    type: "KEYWORD",
    target: "https://www.cloudflarestatus.com/api/v2/status.json",
    port: null,
    expectedStatusRange: "200-299",
    keywordMatch: "\"indicator\"",
    enabled: true,
  },
  {
    name: "npm Status API",
    category: "Developer tools",
    description: "Checks the provider's documented service-health summary endpoint.",
    type: "KEYWORD",
    target: "https://status.npmjs.org/api/v2/status.json",
    port: null,
    expectedStatusRange: "200-299",
    keywordMatch: "\"indicator\"",
    enabled: true,
  },
] as const;
