import { randomBytes } from "node:crypto";
import { hashPassword } from "@/lib/auth";
import { templateDesign } from "@/lib/page-design";
import { closeDatabase, database } from "@/lib/postgres/client";
import type { DatabaseTransaction } from "@/lib/postgres/client";
import { generateAutomationToken } from "@/lib/tokens";
import {
  assertDevelopmentSeedEnabled,
  generateDevelopmentPassword,
  printGeneratedSecrets,
} from "@/scripts/dev-seed";
import { seedDevelopmentRoleUsers } from "@/scripts/seed-role-users";

const SAMPLE_PAGE_SLUGS = ["acme", "api-platform", "consumer-app", "enterprise-customers"];

function daysAgo(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60_000);
}

async function createPage(
  transaction: DatabaseTransaction,
  input: {
    orgId: string;
    name: string;
    slug: string;
    type?: "PUBLIC" | "PRIVATE" | "AUDIENCE";
    isHub?: boolean;
    hubParentId?: string | null;
    passwordHash?: string | null;
  }
) {
  const now = new Date();
  return transaction.insertInto("pages").values({
    orgId: input.orgId,
    name: input.name,
    slug: input.slug,
    type: input.type ?? "PUBLIC",
    isHub: input.isHub ?? false,
    hubParentId: input.hubParentId ?? null,
    timezone: "UTC",
    language: "en",
    headline: input.isHub ? "All Acme services" : "Service Status",
    aboutText: "Development sample data generated by SignalHub.",
    coverImageFit: "CONTAIN",
    coverImagePositionX: 50,
    coverImagePositionY: 50,
    brandColor: "#0f9fab",
    layout: "CENTERED_SUMMARY",
    passwordHash: input.passwordHash ?? null,
    removeBranding: false,
    customCss: null,
    themePreset: "DEFAULT",
    themeMode: "SYSTEM",
    allowThemeOverride: true,
    analyticsEnabled: true,
    publishedDesign: templateDesign("CENTERED_SUMMARY", "#0f9fab"),
    publishedDesignVersion: 1,
    designPublishedAt: now,
    publicVisible: true,
    setupCompletedAt: now,
    deletedAt: null,
    deletedBy: null,
    createdAt: now,
  }).returningAll().executeTakeFirstOrThrow();
}

async function createComponent(
  transaction: DatabaseTransaction,
  input: { pageId: string; groupId?: string | null; name: string; status?: string; order: number }
) {
  const token = generateAutomationToken();
  const component = await transaction.insertInto("components").values({
    pageId: input.pageId,
    groupId: input.groupId ?? null,
    name: input.name,
    description: `${input.name} availability`,
    status: input.status ?? "OPERATIONAL",
    order: input.order,
    visible: true,
    showUptime: true,
    manualStatus: input.status ?? "OPERATIONAL",
    isThirdParty: false,
    thirdPartyProvider: null,
    automationTokenHash: token.hash,
    automationTokenPrefix: token.prefix,
    automationTokenLastFour: token.lastFour,
    createdAt: new Date(),
  }).returningAll().executeTakeFirstOrThrow();
  await transaction.insertInto("componentStatusEvents").values({
    componentId: component.id,
    status: component.status,
    startedAt: daysAgo(30),
    endedAt: null,
    isMaintenance: false,
    note: "Development seed baseline",
  }).execute();
  return component;
}

async function main() {
  assertDevelopmentSeedEnabled("The development sample seed");
  const rolePassword = process.env.DEV_ROLE_PASSWORD || generateDevelopmentPassword();
  await seedDevelopmentRoleUsers({ password: rolePassword });
  const audiencePassword = process.env.DEV_AUDIENCE_PASSWORD || generateDevelopmentPassword();
  const audiencePasswordHash = await hashPassword(audiencePassword);

  await database.transaction().execute(async (transaction) => {
    const organization = await transaction.selectFrom("organizations").selectAll()
      .where("slug", "=", "acme").executeTakeFirstOrThrow();
    await transaction.deleteFrom("pages").where("orgId", "=", organization.id)
      .where("slug", "in", SAMPLE_PAGE_SLUGS).execute();

    const hub = await createPage(transaction, {
      orgId: organization.id,
      name: "Acme Service Hub",
      slug: "acme",
      isHub: true,
    });
    const apiPage = await createPage(transaction, {
      orgId: organization.id,
      name: "API Platform",
      slug: "api-platform",
      hubParentId: hub.id,
    });
    const appPage = await createPage(transaction, {
      orgId: organization.id,
      name: "Consumer Application",
      slug: "consumer-app",
      hubParentId: hub.id,
    });
    const audiencePage = await createPage(transaction, {
      orgId: organization.id,
      name: "Enterprise Customers",
      slug: "enterprise-customers",
      type: "AUDIENCE",
      passwordHash: audiencePasswordHash,
    });

    const apiGroup = await transaction.insertInto("componentGroups").values({
      pageId: apiPage.id,
      name: "Core APIs",
      description: "Primary API services",
      order: 0,
      collapsed: false,
    }).returningAll().executeTakeFirstOrThrow();
    const restApi = await createComponent(transaction, {
      pageId: apiPage.id,
      groupId: apiGroup.id,
      name: "REST API",
      order: 0,
    });
    const graphQl = await createComponent(transaction, {
      pageId: apiPage.id,
      groupId: apiGroup.id,
      name: "GraphQL API",
      order: 1,
    });
    const webApp = await createComponent(transaction, {
      pageId: appPage.id,
      name: "Web Application",
      order: 0,
    });
    const notifications = await createComponent(transaction, {
      pageId: appPage.id,
      name: "Push Notifications",
      status: "DEGRADED_PERFORMANCE",
      order: 1,
    });
    await createComponent(transaction, {
      pageId: audiencePage.id,
      name: "Enterprise API Gateway",
      order: 0,
    });

    const incident = await transaction.insertInto("incidents").values({
      pageId: appPage.id,
      name: "Delayed push notifications",
      status: "MONITORING",
      impact: "MINOR",
      pageWide: false,
      isMaintenance: false,
      maintenanceStatus: null,
      notifySubscribers: true,
      createdAt: daysAgo(1),
      resolvedAt: null,
      backfilled: false,
    }).returningAll().executeTakeFirstOrThrow();
    await transaction.insertInto("incidentComponents").values({
      incidentId: incident.id,
      componentId: notifications.id,
      newStatus: "DEGRADED_PERFORMANCE",
    }).execute();
    await transaction.insertInto("incidentUpdates").values([
      {
        incidentId: incident.id,
        status: "INVESTIGATING",
        body: "The team is investigating elevated notification latency.",
        createdAt: daysAgo(1),
        notified: false,
      },
      {
        incidentId: incident.id,
        status: "MONITORING",
        body: "A mitigation is active and delivery latency is recovering.",
        createdAt: new Date(),
        notified: false,
      },
    ]).execute();

    const metric = await transaction.insertInto("metrics").values({
      pageId: apiPage.id,
      componentId: restApi.id,
      name: "API response time",
      suffix: "ms",
      description: "Median response time",
      visible: true,
      decimals: 0,
    }).returningAll().executeTakeFirstOrThrow();
    const points = Array.from({ length: 48 }, (_, index) => ({
      metricId: metric.id,
      timestamp: new Date(Date.now() - (47 - index) * 60 * 60_000),
      value: 85 + Math.round(20 * Math.sin(index / 5)) + (index > 40 ? 25 : 0),
    }));
    await transaction.insertInto("metricPoints").values(points).execute();

    await transaction.insertInto("monitorTemplates").values({
      name: "Development HTTP check",
      category: "HTTP",
      description: "Disabled example monitor template",
      type: "HTTP",
      target: "https://example.com",
      port: null,
      expectedStatusRange: "200-299",
      keywordMatch: null,
      enabled: false,
    }).onConflict((conflict) => conflict.column("name").doUpdateSet({
      description: "Disabled example monitor template",
      enabled: false,
    })).execute();

    await transaction.insertInto("subscribers").values([
      {
        pageId: apiPage.id,
        channel: "EMAIL",
        contact: "developer@example.com",
        componentIds: [restApi.id, graphQl.id],
        eventTypes: [],
        verified: true,
        quarantined: false,
        unsubscribeToken: randomBytes(32).toString("hex"),
      },
      {
        pageId: appPage.id,
        channel: "EMAIL",
        contact: "customer@example.com",
        componentIds: [webApp.id],
        eventTypes: [],
        verified: true,
        quarantined: false,
        unsubscribeToken: randomBytes(32).toString("hex"),
      },
    ]).execute();

    const accessGroup = await transaction.insertInto("pageAccessGroups").values({
      pageId: audiencePage.id,
      name: "Enterprise audience",
      componentIds: [],
    }).returningAll().executeTakeFirstOrThrow();
    await transaction.insertInto("pageAccessUsers").values({
      pageId: audiencePage.id,
      email: "enterprise@example.com",
      passwordHash: audiencePasswordHash,
      groupId: accessGroup.id,
      componentIds: [],
      createdAt: new Date(),
    }).execute();

  });

  printGeneratedSecrets("Development sample seed", [
    { label: "Shared role password", value: rolePassword },
    { label: "Audience page password", value: audiencePassword },
  ]);
  console.log("PostgreSQL development sample data created.");
}

main()
  .catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  })
  .finally(() => closeDatabase());
